### PR TITLE
Maintenance: bump Node, typescript and type-fest

### PR DESCRIPTION
**Pull request by lolmaus**
I'm working on introducing TypeDoc to https://github.com/ef4/scenario-tester/ . It chokes on a type issue in `type-fest` thorugh `fixturify-projects`.

I've confirmed locally that bumping `type-fest` here resolves the issue.

But bumping `type-fest` pulls bumping `typescript` which in turn requires bumping Node.

PS I also attempted replacing `yarn` with `pnpm`, but it caused the CI pipeline to break, and I failed to figure it out.

### CODE REVIEW

**Comment by ef4** [comment]
Thanks, looks good.

For anybody else concerned about breaking changes: this is only bumping the version we use for compiling node-fixturify-project itself, not the minimum version supported for users of the library, so this is non-breaking.

(We could also do a breaking major that drops old nodes, but that would be a separate change.)

**Comment by ef4** [comment]
(I didn't notice under after merging this that CI didn't even run. I will check on that too.)

**Comment by ef4** [comment]
Ah, so this breaks node 14 `yarn install` because of the engines declaration in type-fest. Which is silly for a types-only package, and the package does in fact work perfectly fine on node 14 if you ignore the error. But we can't ask all users to ignore the error.

So this will need to go out as a breaking semver major.

**Comment by ef4** [comment]
@lolmaus can you please do a follow up that
 -  drops node 14 from the test matrix and the engines declaration
 - removes all methods that are already marked deprecated (I see `root` and `writeSync`)

**Comment by lolmaus** [comment]
Follow up PR: https://github.com/stefanpenner/node-fixturify-project/pull/85 .

**Pull request merged**
